version: 2.1
jobs:
  build:    
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [node_modules]
      - run:
          name: Build app
          command: |
            npm install
            npm run build
      - save_cache:
          paths: [node_modules]
          key: node_modules
  lint:    
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [node_modules]
      - run:
          name: lint app
          command: |
            npm install
            npm run lint
  test:    
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [node_modules]
      - run:
          name: test app
          command: |
            npm install
            npm run test
workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - lint:
          requires: [build]
