version: 2.1
jobs:
  build:    
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [node_modules]
      - run:
          name: Build app
          command: |
            npm install
            npm run build
      - save_cache:
          paths: [node_modules]
          key: node_modules
  lint:    
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [node_modules]
      - run:
          name: lint app
          command: |
            npm install
            npm run lint
  test:    
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [node_modules]
      - run:
          name: test app
          command: |
            npm install
            npm run test
  pushToDockerhub:    
    docker:
      - image: circleci/node:13.8.0
        auth:
          username: $username
          password: $password
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: push to docker hub
          command: |
            chmod +x upload_docker.sh
            docker build --tag=essameid614/udacity_nanodegree_capstone:latest .
            ./upload_docker.sh
  
#start deployment
#create the image to be deployed to docker hub
#deploy the image to docker hub
#create the eks cluster 
#deploy the app to the eks cluster 

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - lint:
          requires: [build]
      - pushToDockerhub:
          context: docker-context
          requires: [test, lint]
